### ISSUE TITLE
Mimas’ SoI seems very, very low

### ISSUE THREAD

**Issue by meyerweb** [pap1723/RSSResonantOrbits#2]
I honestly don’t know if this is a bug, since I haven’t played RSS and couldn’t dig up any planetary-characteristic pages for RSS.

At present, Mimas’ SoI shows as 249.6km above the moon’s surface.  If this is in fact correct, feel free to close this out WONTFIX.  (And please comment to say so, because if so, my code may need some touch-ups to handle situations like this.)

**Comment by pap1723** [comment]
Yes, this is actually true! With Mimas being so tiny and in such close proximity to massive Saturn, it has a tiny, tiny SOI. Very similar to Phobos and Deimos.

**Comment by meyerweb** [comment]
Makes sense; thanks!  I’ll grab that latest and see how the experience is—I suspect there’s room for warning messages or other changes, in situations like this one.
