### ISSUE TITLE
Layout gets slightly borked by the footer

### ISSUE THREAD

**Issue by meyerweb** [pap1723/RSSResonantOrbits#3]
I discovered that the removal of one of the two `span` elements in your `footer` caused the layout to blow out to full-browser-width even on desktop.  This was unexpected, and I’m looking forward to working out why it happened!  But if you put a `span` back, even if it’s just `<span></span>`, the layout won’t go full-width.

**Comment by pap1723** [comment]
Fixed. Thank you!
